//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credipaz.Comercio.Web.CommerceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/Credipaz.Tarjeta.Shared.Models")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityStamp {
            get {
                return this.SecurityStampField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityStampField, value) != true)) {
                    this.SecurityStampField = value;
                    this.RaisePropertyChanged("SecurityStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoModel", Namespace="http://schemas.datacontract.org/2004/07/Credipaz.Tarjeta.Shared.Models")]
    [System.SerializableAttribute()]
    public partial class InfoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCommerceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSubsidiaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubsidiaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUIT {
            get {
                return this.CUITField;
            }
            set {
                if ((object.ReferenceEquals(this.CUITField, value) != true)) {
                    this.CUITField = value;
                    this.RaisePropertyChanged("CUIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyFullName {
            get {
                return this.CompanyFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyFullNameField, value) != true)) {
                    this.CompanyFullNameField = value;
                    this.RaisePropertyChanged("CompanyFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCommerce {
            get {
                return this.IdCommerceField;
            }
            set {
                if ((this.IdCommerceField.Equals(value) != true)) {
                    this.IdCommerceField = value;
                    this.RaisePropertyChanged("IdCommerce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSubsidiary {
            get {
                return this.IdSubsidiaryField;
            }
            set {
                if ((this.IdSubsidiaryField.Equals(value) != true)) {
                    this.IdSubsidiaryField = value;
                    this.RaisePropertyChanged("IdSubsidiary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCode {
            get {
                return this.LocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCodeField, value) != true)) {
                    this.LocationCodeField = value;
                    this.RaisePropertyChanged("LocationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvinceCode {
            get {
                return this.ProvinceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceCodeField, value) != true)) {
                    this.ProvinceCodeField = value;
                    this.RaisePropertyChanged("ProvinceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subsidiary {
            get {
                return this.SubsidiaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubsidiaryField, value) != true)) {
                    this.SubsidiaryField = value;
                    this.RaisePropertyChanged("Subsidiary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditModel", Namespace="http://schemas.datacontract.org/2004/07/Credipaz.Tarjeta.Shared.Models")]
    [System.SerializableAttribute()]
    public partial class CreditModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DniNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdLogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonthlyIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OcupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestedAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DniNumber {
            get {
                return this.DniNumberField;
            }
            set {
                if ((this.DniNumberField.Equals(value) != true)) {
                    this.DniNumberField = value;
                    this.RaisePropertyChanged("DniNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DniType {
            get {
                return this.DniTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DniTypeField, value) != true)) {
                    this.DniTypeField = value;
                    this.RaisePropertyChanged("DniType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdLog {
            get {
                return this.IdLogField;
            }
            set {
                if ((this.IdLogField.Equals(value) != true)) {
                    this.IdLogField = value;
                    this.RaisePropertyChanged("IdLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MonthlyIncome {
            get {
                return this.MonthlyIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.MonthlyIncomeField, value) != true)) {
                    this.MonthlyIncomeField = value;
                    this.RaisePropertyChanged("MonthlyIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ocupation {
            get {
                return this.OcupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OcupationField, value) != true)) {
                    this.OcupationField = value;
                    this.RaisePropertyChanged("Ocupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quotas {
            get {
                return this.QuotasField;
            }
            set {
                if ((this.QuotasField.Equals(value) != true)) {
                    this.QuotasField = value;
                    this.RaisePropertyChanged("Quotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestedAmount {
            get {
                return this.RequestedAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedAmountField, value) != true)) {
                    this.RequestedAmountField = value;
                    this.RaisePropertyChanged("RequestedAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditDetailModel", Namespace="http://schemas.datacontract.org/2004/07/Credipaz.Tarjeta.Shared.Models")]
    [System.SerializableAttribute()]
    public partial class CreditDetailModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AdmissionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HousingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdHousingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdJobFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdNationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdOcupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdQuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdSellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTelRel1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTelRel2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTelRel3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTelType1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTelType2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTelType3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdWorkLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdWorkProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontlyIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OcupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubsidiaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxQuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelRel1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelRel2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelRel3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelType1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelType2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelType3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkAddressNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkingTelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressNumber {
            get {
                return this.AddressNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNumberField, value) != true)) {
                    this.AddressNumberField = value;
                    this.RaisePropertyChanged("AddressNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AdmissionDate {
            get {
                return this.AdmissionDateField;
            }
            set {
                if ((this.AdmissionDateField.Equals(value) != true)) {
                    this.AdmissionDateField = value;
                    this.RaisePropertyChanged("AdmissionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUIL {
            get {
                return this.CUILField;
            }
            set {
                if ((object.ReferenceEquals(this.CUILField, value) != true)) {
                    this.CUILField = value;
                    this.RaisePropertyChanged("CUIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUIT {
            get {
                return this.CUITField;
            }
            set {
                if ((object.ReferenceEquals(this.CUITField, value) != true)) {
                    this.CUITField = value;
                    this.RaisePropertyChanged("CUIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((this.DNIField.Equals(value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Housing {
            get {
                return this.HousingField;
            }
            set {
                if ((object.ReferenceEquals(this.HousingField, value) != true)) {
                    this.HousingField = value;
                    this.RaisePropertyChanged("Housing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdHousing {
            get {
                return this.IdHousingField;
            }
            set {
                if ((this.IdHousingField.Equals(value) != true)) {
                    this.IdHousingField = value;
                    this.RaisePropertyChanged("IdHousing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdJobField {
            get {
                return this.IdJobFieldField;
            }
            set {
                if ((this.IdJobFieldField.Equals(value) != true)) {
                    this.IdJobFieldField = value;
                    this.RaisePropertyChanged("IdJobField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdLocation {
            get {
                return this.IdLocationField;
            }
            set {
                if ((this.IdLocationField.Equals(value) != true)) {
                    this.IdLocationField = value;
                    this.RaisePropertyChanged("IdLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMaritalStatus {
            get {
                return this.IdMaritalStatusField;
            }
            set {
                if ((this.IdMaritalStatusField.Equals(value) != true)) {
                    this.IdMaritalStatusField = value;
                    this.RaisePropertyChanged("IdMaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdNationality {
            get {
                return this.IdNationalityField;
            }
            set {
                if ((this.IdNationalityField.Equals(value) != true)) {
                    this.IdNationalityField = value;
                    this.RaisePropertyChanged("IdNationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdOcupation {
            get {
                return this.IdOcupationField;
            }
            set {
                if ((this.IdOcupationField.Equals(value) != true)) {
                    this.IdOcupationField = value;
                    this.RaisePropertyChanged("IdOcupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdProvince {
            get {
                return this.IdProvinceField;
            }
            set {
                if ((this.IdProvinceField.Equals(value) != true)) {
                    this.IdProvinceField = value;
                    this.RaisePropertyChanged("IdProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdQuota {
            get {
                return this.IdQuotaField;
            }
            set {
                if ((this.IdQuotaField.Equals(value) != true)) {
                    this.IdQuotaField = value;
                    this.RaisePropertyChanged("IdQuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdSeller {
            get {
                return this.IdSellerField;
            }
            set {
                if ((this.IdSellerField.Equals(value) != true)) {
                    this.IdSellerField = value;
                    this.RaisePropertyChanged("IdSeller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTelRel1 {
            get {
                return this.IdTelRel1Field;
            }
            set {
                if ((this.IdTelRel1Field.Equals(value) != true)) {
                    this.IdTelRel1Field = value;
                    this.RaisePropertyChanged("IdTelRel1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTelRel2 {
            get {
                return this.IdTelRel2Field;
            }
            set {
                if ((this.IdTelRel2Field.Equals(value) != true)) {
                    this.IdTelRel2Field = value;
                    this.RaisePropertyChanged("IdTelRel2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTelRel3 {
            get {
                return this.IdTelRel3Field;
            }
            set {
                if ((this.IdTelRel3Field.Equals(value) != true)) {
                    this.IdTelRel3Field = value;
                    this.RaisePropertyChanged("IdTelRel3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTelType1 {
            get {
                return this.IdTelType1Field;
            }
            set {
                if ((this.IdTelType1Field.Equals(value) != true)) {
                    this.IdTelType1Field = value;
                    this.RaisePropertyChanged("IdTelType1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTelType2 {
            get {
                return this.IdTelType2Field;
            }
            set {
                if ((this.IdTelType2Field.Equals(value) != true)) {
                    this.IdTelType2Field = value;
                    this.RaisePropertyChanged("IdTelType2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTelType3 {
            get {
                return this.IdTelType3Field;
            }
            set {
                if ((this.IdTelType3Field.Equals(value) != true)) {
                    this.IdTelType3Field = value;
                    this.RaisePropertyChanged("IdTelType3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdWorkLocation {
            get {
                return this.IdWorkLocationField;
            }
            set {
                if ((this.IdWorkLocationField.Equals(value) != true)) {
                    this.IdWorkLocationField = value;
                    this.RaisePropertyChanged("IdWorkLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdWorkProvince {
            get {
                return this.IdWorkProvinceField;
            }
            set {
                if ((this.IdWorkProvinceField.Equals(value) != true)) {
                    this.IdWorkProvinceField = value;
                    this.RaisePropertyChanged("IdWorkProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobField {
            get {
                return this.JobFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.JobFieldField, value) != true)) {
                    this.JobFieldField = value;
                    this.RaisePropertyChanged("JobField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontlyIncome {
            get {
                return this.MontlyIncomeField;
            }
            set {
                if ((this.MontlyIncomeField.Equals(value) != true)) {
                    this.MontlyIncomeField = value;
                    this.RaisePropertyChanged("MontlyIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obs {
            get {
                return this.ObsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObsField, value) != true)) {
                    this.ObsField = value;
                    this.RaisePropertyChanged("Obs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ocupation {
            get {
                return this.OcupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OcupationField, value) != true)) {
                    this.OcupationField = value;
                    this.RaisePropertyChanged("Ocupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Plan {
            get {
                return this.PlanField;
            }
            set {
                if ((this.PlanField.Equals(value) != true)) {
                    this.PlanField = value;
                    this.RaisePropertyChanged("Plan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quota {
            get {
                return this.QuotaField;
            }
            set {
                if ((this.QuotaField.Equals(value) != true)) {
                    this.QuotaField = value;
                    this.RaisePropertyChanged("Quota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seller {
            get {
                return this.SellerField;
            }
            set {
                if ((object.ReferenceEquals(this.SellerField, value) != true)) {
                    this.SellerField = value;
                    this.RaisePropertyChanged("Seller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subsidiary {
            get {
                return this.SubsidiaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubsidiaryField, value) != true)) {
                    this.SubsidiaryField = value;
                    this.RaisePropertyChanged("Subsidiary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxQuota {
            get {
                return this.TaxQuotaField;
            }
            set {
                if ((this.TaxQuotaField.Equals(value) != true)) {
                    this.TaxQuotaField = value;
                    this.RaisePropertyChanged("TaxQuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel1 {
            get {
                return this.Tel1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Tel1Field, value) != true)) {
                    this.Tel1Field = value;
                    this.RaisePropertyChanged("Tel1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel2 {
            get {
                return this.Tel2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Tel2Field, value) != true)) {
                    this.Tel2Field = value;
                    this.RaisePropertyChanged("Tel2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel3 {
            get {
                return this.Tel3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Tel3Field, value) != true)) {
                    this.Tel3Field = value;
                    this.RaisePropertyChanged("Tel3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelRel1 {
            get {
                return this.TelRel1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TelRel1Field, value) != true)) {
                    this.TelRel1Field = value;
                    this.RaisePropertyChanged("TelRel1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelRel2 {
            get {
                return this.TelRel2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TelRel2Field, value) != true)) {
                    this.TelRel2Field = value;
                    this.RaisePropertyChanged("TelRel2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelRel3 {
            get {
                return this.TelRel3Field;
            }
            set {
                if ((object.ReferenceEquals(this.TelRel3Field, value) != true)) {
                    this.TelRel3Field = value;
                    this.RaisePropertyChanged("TelRel3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelType1 {
            get {
                return this.TelType1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TelType1Field, value) != true)) {
                    this.TelType1Field = value;
                    this.RaisePropertyChanged("TelType1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelType2 {
            get {
                return this.TelType2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TelType2Field, value) != true)) {
                    this.TelType2Field = value;
                    this.RaisePropertyChanged("TelType2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelType3 {
            get {
                return this.TelType3Field;
            }
            set {
                if ((object.ReferenceEquals(this.TelType3Field, value) != true)) {
                    this.TelType3Field = value;
                    this.RaisePropertyChanged("TelType3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkAddress {
            get {
                return this.WorkAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAddressField, value) != true)) {
                    this.WorkAddressField = value;
                    this.RaisePropertyChanged("WorkAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkAddressNumber {
            get {
                return this.WorkAddressNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAddressNumberField, value) != true)) {
                    this.WorkAddressNumberField = value;
                    this.RaisePropertyChanged("WorkAddressNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkFile {
            get {
                return this.WorkFileField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkFileField, value) != true)) {
                    this.WorkFileField = value;
                    this.RaisePropertyChanged("WorkFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkLocation {
            get {
                return this.WorkLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkLocationField, value) != true)) {
                    this.WorkLocationField = value;
                    this.RaisePropertyChanged("WorkLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkPostalCode {
            get {
                return this.WorkPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPostalCodeField, value) != true)) {
                    this.WorkPostalCodeField = value;
                    this.RaisePropertyChanged("WorkPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkProvince {
            get {
                return this.WorkProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkProvinceField, value) != true)) {
                    this.WorkProvinceField = value;
                    this.RaisePropertyChanged("WorkProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkingTel {
            get {
                return this.WorkingTelField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingTelField, value) != true)) {
                    this.WorkingTelField = value;
                    this.RaisePropertyChanged("WorkingTel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericObject", Namespace="http://schemas.datacontract.org/2004/07/Credipaz.Tarjeta.Shared.Models")]
    [System.SerializableAttribute()]
    public partial class GenericObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxModel", Namespace="http://schemas.datacontract.org/2004/07/Credipaz.Tarjeta.Shared.Models")]
    [System.SerializableAttribute()]
    public partial class TaxModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CoefficientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short QuotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Coefficient {
            get {
                return this.CoefficientField;
            }
            set {
                if ((this.CoefficientField.Equals(value) != true)) {
                    this.CoefficientField = value;
                    this.RaisePropertyChanged("Coefficient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Quota {
            get {
                return this.QuotaField;
            }
            set {
                if ((this.QuotaField.Equals(value) != true)) {
                    this.QuotaField = value;
                    this.RaisePropertyChanged("Quota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Condition", Namespace="http://schemas.datacontract.org/2004/07/Credipaz.Tarjeta.Shared.Models")]
    [System.SerializableAttribute()]
    public partial class Condition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Concept {
            get {
                return this.ConceptField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptField, value) != true)) {
                    this.ConceptField = value;
                    this.RaisePropertyChanged("Concept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Initial {
            get {
                return this.InitialField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialField, value) != true)) {
                    this.InitialField = value;
                    this.RaisePropertyChanged("Initial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommerceService.IComercioService")]
    public interface IComercioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetUserIdentification", ReplyAction="http://tempuri.org/IComercioService/GetUserIdentificationResponse")]
        Credipaz.Comercio.Web.CommerceService.UserModel GetUserIdentification(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetUserIdentification", ReplyAction="http://tempuri.org/IComercioService/GetUserIdentificationResponse")]
        System.Threading.Tasks.Task<Credipaz.Comercio.Web.CommerceService.UserModel> GetUserIdentificationAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetUserInfo", ReplyAction="http://tempuri.org/IComercioService/GetUserInfoResponse")]
        Credipaz.Comercio.Web.CommerceService.InfoModel GetUserInfo(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetUserInfo", ReplyAction="http://tempuri.org/IComercioService/GetUserInfoResponse")]
        System.Threading.Tasks.Task<Credipaz.Comercio.Web.CommerceService.InfoModel> GetUserInfoAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCredits", ReplyAction="http://tempuri.org/IComercioService/GetCreditsResponse")]
        System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.CreditModel> GetCredits(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCredits", ReplyAction="http://tempuri.org/IComercioService/GetCreditsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.CreditModel>> GetCreditsAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCreditDetail", ReplyAction="http://tempuri.org/IComercioService/GetCreditDetailResponse")]
        Credipaz.Comercio.Web.CommerceService.CreditDetailModel GetCreditDetail(int idLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCreditDetail", ReplyAction="http://tempuri.org/IComercioService/GetCreditDetailResponse")]
        System.Threading.Tasks.Task<Credipaz.Comercio.Web.CommerceService.CreditDetailModel> GetCreditDetailAsync(int idLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCommerceSellers", ReplyAction="http://tempuri.org/IComercioService/GetCommerceSellersResponse")]
        System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.GenericObject> GetCommerceSellers(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCommerceSellers", ReplyAction="http://tempuri.org/IComercioService/GetCommerceSellersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.GenericObject>> GetCommerceSellersAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCommercePlans", ReplyAction="http://tempuri.org/IComercioService/GetCommercePlansResponse")]
        System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.GenericObject> GetCommercePlans(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCommercePlans", ReplyAction="http://tempuri.org/IComercioService/GetCommercePlansResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.GenericObject>> GetCommercePlansAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCommerceQuotas", ReplyAction="http://tempuri.org/IComercioService/GetCommerceQuotasResponse")]
        System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.TaxModel> GetCommerceQuotas(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetCommerceQuotas", ReplyAction="http://tempuri.org/IComercioService/GetCommerceQuotasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.TaxModel>> GetCommerceQuotasAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/SaveForm", ReplyAction="http://tempuri.org/IComercioService/SaveFormResponse")]
        bool SaveForm(Credipaz.Comercio.Web.CommerceService.CreditDetailModel formData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/SaveForm", ReplyAction="http://tempuri.org/IComercioService/SaveFormResponse")]
        System.Threading.Tasks.Task<bool> SaveFormAsync(Credipaz.Comercio.Web.CommerceService.CreditDetailModel formData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetConditions", ReplyAction="http://tempuri.org/IComercioService/GetConditionsResponse")]
        System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.Condition> GetConditions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComercioService/GetConditions", ReplyAction="http://tempuri.org/IComercioService/GetConditionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.Condition>> GetConditionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComercioServiceChannel : Credipaz.Comercio.Web.CommerceService.IComercioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComercioServiceClient : System.ServiceModel.ClientBase<Credipaz.Comercio.Web.CommerceService.IComercioService>, Credipaz.Comercio.Web.CommerceService.IComercioService {
        
        public ComercioServiceClient() {
        }
        
        public ComercioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComercioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComercioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComercioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Credipaz.Comercio.Web.CommerceService.UserModel GetUserIdentification(int idUser) {
            return base.Channel.GetUserIdentification(idUser);
        }
        
        public System.Threading.Tasks.Task<Credipaz.Comercio.Web.CommerceService.UserModel> GetUserIdentificationAsync(int idUser) {
            return base.Channel.GetUserIdentificationAsync(idUser);
        }
        
        public Credipaz.Comercio.Web.CommerceService.InfoModel GetUserInfo(int idUser) {
            return base.Channel.GetUserInfo(idUser);
        }
        
        public System.Threading.Tasks.Task<Credipaz.Comercio.Web.CommerceService.InfoModel> GetUserInfoAsync(int idUser) {
            return base.Channel.GetUserInfoAsync(idUser);
        }
        
        public System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.CreditModel> GetCredits(int idUser) {
            return base.Channel.GetCredits(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.CreditModel>> GetCreditsAsync(int idUser) {
            return base.Channel.GetCreditsAsync(idUser);
        }
        
        public Credipaz.Comercio.Web.CommerceService.CreditDetailModel GetCreditDetail(int idLog) {
            return base.Channel.GetCreditDetail(idLog);
        }
        
        public System.Threading.Tasks.Task<Credipaz.Comercio.Web.CommerceService.CreditDetailModel> GetCreditDetailAsync(int idLog) {
            return base.Channel.GetCreditDetailAsync(idLog);
        }
        
        public System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.GenericObject> GetCommerceSellers(int idUser) {
            return base.Channel.GetCommerceSellers(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.GenericObject>> GetCommerceSellersAsync(int idUser) {
            return base.Channel.GetCommerceSellersAsync(idUser);
        }
        
        public System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.GenericObject> GetCommercePlans(int idUser) {
            return base.Channel.GetCommercePlans(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.GenericObject>> GetCommercePlansAsync(int idUser) {
            return base.Channel.GetCommercePlansAsync(idUser);
        }
        
        public System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.TaxModel> GetCommerceQuotas(int idUser) {
            return base.Channel.GetCommerceQuotas(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.TaxModel>> GetCommerceQuotasAsync(int idUser) {
            return base.Channel.GetCommerceQuotasAsync(idUser);
        }
        
        public bool SaveForm(Credipaz.Comercio.Web.CommerceService.CreditDetailModel formData) {
            return base.Channel.SaveForm(formData);
        }
        
        public System.Threading.Tasks.Task<bool> SaveFormAsync(Credipaz.Comercio.Web.CommerceService.CreditDetailModel formData) {
            return base.Channel.SaveFormAsync(formData);
        }
        
        public System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.Condition> GetConditions() {
            return base.Channel.GetConditions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Credipaz.Comercio.Web.CommerceService.Condition>> GetConditionsAsync() {
            return base.Channel.GetConditionsAsync();
        }
    }
}
