//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credipaz.Comercio.Web.ScoringService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosEntradaScoring", Namespace="http://schemas.datacontract.org/2004/07/wcfScoring")]
    [System.SerializableAttribute()]
    public partial class ParametrosEntradaScoring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nDisponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nIDComercianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nIngresoMensualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nLimiteCuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nMontoSolicitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCanalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sLKOcupacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sLugarConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nDisponible {
            get {
                return this.nDisponibleField;
            }
            set {
                if ((this.nDisponibleField.Equals(value) != true)) {
                    this.nDisponibleField = value;
                    this.RaisePropertyChanged("nDisponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nIDComerciante {
            get {
                return this.nIDComercianteField;
            }
            set {
                if ((this.nIDComercianteField.Equals(value) != true)) {
                    this.nIDComercianteField = value;
                    this.RaisePropertyChanged("nIDComerciante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nIngresoMensual {
            get {
                return this.nIngresoMensualField;
            }
            set {
                if ((this.nIngresoMensualField.Equals(value) != true)) {
                    this.nIngresoMensualField = value;
                    this.RaisePropertyChanged("nIngresoMensual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nLimiteCuotas {
            get {
                return this.nLimiteCuotasField;
            }
            set {
                if ((this.nLimiteCuotasField.Equals(value) != true)) {
                    this.nLimiteCuotasField = value;
                    this.RaisePropertyChanged("nLimiteCuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nMontoSolicitado {
            get {
                return this.nMontoSolicitadoField;
            }
            set {
                if ((this.nMontoSolicitadoField.Equals(value) != true)) {
                    this.nMontoSolicitadoField = value;
                    this.RaisePropertyChanged("nMontoSolicitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCanal {
            get {
                return this.sCanalField;
            }
            set {
                if ((object.ReferenceEquals(this.sCanalField, value) != true)) {
                    this.sCanalField = value;
                    this.RaisePropertyChanged("sCanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sLKOcupacion {
            get {
                return this.sLKOcupacionField;
            }
            set {
                if ((object.ReferenceEquals(this.sLKOcupacionField, value) != true)) {
                    this.sLKOcupacionField = value;
                    this.RaisePropertyChanged("sLKOcupacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sLugarConsulta {
            get {
                return this.sLugarConsultaField;
            }
            set {
                if ((object.ReferenceEquals(this.sLugarConsultaField, value) != true)) {
                    this.sLugarConsultaField = value;
                    this.RaisePropertyChanged("sLugarConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sProducto {
            get {
                return this.sProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.sProductoField, value) != true)) {
                    this.sProductoField = value;
                    this.RaisePropertyChanged("sProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sTipo {
            get {
                return this.sTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.sTipoField, value) != true)) {
                    this.sTipoField = value;
                    this.RaisePropertyChanged("sTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sValor {
            get {
                return this.sValorField;
            }
            set {
                if ((object.ReferenceEquals(this.sValorField, value) != true)) {
                    this.sValorField = value;
                    this.RaisePropertyChanged("sValor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScoringService.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CalcularCuil", ReplyAction="http://tempuri.org/IServicio/CalcularCuilResponse")]
        string CalcularCuil(string sSexo, int nDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CalcularCuil", ReplyAction="http://tempuri.org/IServicio/CalcularCuilResponse")]
        System.Threading.Tasks.Task<string> CalcularCuilAsync(string sSexo, int nDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EsFecha", ReplyAction="http://tempuri.org/IServicio/EsFechaResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Credipaz.Comercio.Web.ScoringService.ParametrosEntradaScoring))]
        bool EsFecha(object value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EsFecha", ReplyAction="http://tempuri.org/IServicio/EsFechaResponse")]
        System.Threading.Tasks.Task<bool> EsFechaAsync(object value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EsNumerico", ReplyAction="http://tempuri.org/IServicio/EsNumericoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Credipaz.Comercio.Web.ScoringService.ParametrosEntradaScoring))]
        bool EsNumerico(object value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EsNumerico", ReplyAction="http://tempuri.org/IServicio/EsNumericoResponse")]
        System.Threading.Tasks.Task<bool> EsNumericoAsync(object value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerScoring", ReplyAction="http://tempuri.org/IServicio/ObtenerScoringResponse")]
        System.Data.DataTable ObtenerScoring(Credipaz.Comercio.Web.ScoringService.ParametrosEntradaScoring Datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerScoring", ReplyAction="http://tempuri.org/IServicio/ObtenerScoringResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerScoringAsync(Credipaz.Comercio.Web.ScoringService.ParametrosEntradaScoring Datos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : Credipaz.Comercio.Web.ScoringService.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<Credipaz.Comercio.Web.ScoringService.IServicio>, Credipaz.Comercio.Web.ScoringService.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CalcularCuil(string sSexo, int nDNI) {
            return base.Channel.CalcularCuil(sSexo, nDNI);
        }
        
        public System.Threading.Tasks.Task<string> CalcularCuilAsync(string sSexo, int nDNI) {
            return base.Channel.CalcularCuilAsync(sSexo, nDNI);
        }
        
        public bool EsFecha(object value) {
            return base.Channel.EsFecha(value);
        }
        
        public System.Threading.Tasks.Task<bool> EsFechaAsync(object value) {
            return base.Channel.EsFechaAsync(value);
        }
        
        public bool EsNumerico(object value) {
            return base.Channel.EsNumerico(value);
        }
        
        public System.Threading.Tasks.Task<bool> EsNumericoAsync(object value) {
            return base.Channel.EsNumericoAsync(value);
        }
        
        public System.Data.DataTable ObtenerScoring(Credipaz.Comercio.Web.ScoringService.ParametrosEntradaScoring Datos) {
            return base.Channel.ObtenerScoring(Datos);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerScoringAsync(Credipaz.Comercio.Web.ScoringService.ParametrosEntradaScoring Datos) {
            return base.Channel.ObtenerScoringAsync(Datos);
        }
    }
}
