//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso.
        /// </summary>
        internal static string AdmissionDate {
            get {
                return ResourceManager.GetString("AdmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya se encuentra Registrado?.
        /// </summary>
        internal static string AlreadySignedUp {
            get {
                return ResourceManager.GetString("AlreadySignedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANU.
        /// </summary>
        internal static string Annulled {
            get {
                return ResourceManager.GetString("Annulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed de Comercio.
        /// </summary>
        internal static string AplicationName {
            get {
                return ResourceManager.GetString("AplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre Calles.
        /// </summary>
        internal static string BetweenStreets {
            get {
                return ResourceManager.GetString("BetweenStreets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Nac..
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chequear los datos Ingresados.
        /// </summary>
        internal static string CheckData {
            get {
                return ResourceManager.GetString("CheckData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string CodeResult {
            get {
                return ResourceManager.GetString("CodeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion Crediticia del Comercio..
        /// </summary>
        internal static string CommerceCreditInfo {
            get {
                return ResourceManager.GetString("CommerceCreditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Comercio..
        /// </summary>
        internal static string CommerceData {
            get {
                return ResourceManager.GetString("CommerceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCO.
        /// </summary>
        internal static string CommercePreAuthorized {
            get {
                return ResourceManager.GetString("CommercePreAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completar Informacion del Credito.
        /// </summary>
        internal static string CompleteCredit {
            get {
                return ResourceManager.GetString("CompleteCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string Consult {
            get {
                return ResourceManager.GetString("Consult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSUMO.
        /// </summary>
        internal static string Consuption {
            get {
                return ResourceManager.GetString("Consuption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcto.
        /// </summary>
        internal static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas Correctas.
        /// </summary>
        internal static string CorrectQuestions {
            get {
                return ResourceManager.GetString("CorrectQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Formulario fue Guardado Satisfactoriamente.
        /// </summary>
        internal static string CorrectSaveData {
            get {
                return ResourceManager.GetString("CorrectSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La infomación fue enviada correctamente!.
        /// </summary>
        internal static string CorrectSendData {
            get {
                return ResourceManager.GetString("CorrectSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nueva Cuenta.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario de Pre-Aprobacion de Credito.
        /// </summary>
        internal static string CreditForm {
            get {
                return ResourceManager.GetString("CreditForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de Crédito.
        /// </summary>
        internal static string CreditIncrease {
            get {
                return ResourceManager.GetString("CreditIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de Creditos.
        /// </summary>
        internal static string CreditsDetails {
            get {
                return ResourceManager.GetString("CreditsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIL.
        /// </summary>
        internal static string CUIL {
            get {
                return ResourceManager.GetString("CUIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.U.I.T..
        /// </summary>
        internal static string CUIT {
            get {
                return ResourceManager.GetString("CUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        internal static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro. Doc..
        /// </summary>
        internal static string DocNumber {
            get {
                return ResourceManager.GetString("DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Doc..
        /// </summary>
        internal static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femenino.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Todavía no se Registro?.
        /// </summary>
        internal static string FirstTime {
            get {
                return ResourceManager.GetString("FirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Formulario se guardo exitosamente!.
        /// </summary>
        internal static string FormSaved {
            get {
                return ResourceManager.GetString("FormSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizacion pendiente de aprobacion, Verificar estado.
        /// </summary>
        internal static string FormSavedPending {
            get {
                return ResourceManager.GetString("FormSavedPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido y Nombre(s).
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Locación.
        /// </summary>
        internal static string GeoLocation {
            get {
                return ResourceManager.GetString("GeoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vivienda.
        /// </summary>
        internal static string Housing {
            get {
                return ResourceManager.GetString("Housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        internal static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario para Validacion de Identidades.
        /// </summary>
        internal static string IdentityValidator {
            get {
                return ResourceManager.GetString("IdentityValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Usuario.
        /// </summary>
        internal static string IdUser {
            get {
                return ResourceManager.GetString("IdUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrecto.
        /// </summary>
        internal static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! El Formulario no pudo ser Guardado.
        /// </summary>
        internal static string InCorrectSaveData {
            get {
                return ResourceManager.GetString("InCorrectSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información no pudo ser enviada.. Reintente mas tarde.
        /// </summary>
        internal static string IncorrectSendData {
            get {
                return ResourceManager.GetString("IncorrectSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese a su Cuenta.
        /// </summary>
        internal static string InputAccount {
            get {
                return ResourceManager.GetString("InputAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubro.
        /// </summary>
        internal static string JobField {
            get {
                return ResourceManager.GetString("JobField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Laborales.
        /// </summary>
        internal static string LaboralData {
            get {
                return ResourceManager.GetString("LaboralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario de Inicio de Sesión.
        /// </summary>
        internal static string LogInForm {
            get {
                return ResourceManager.GetString("LogInForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        internal static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad Superada para Alta de Credito.
        /// </summary>
        internal static string MaxAgeCredit {
            get {
                return ResourceManager.GetString("MaxAgeCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese una direccion de mail valida.
        /// </summary>
        internal static string MessageMail {
            get {
                return ResourceManager.GetString("MessageMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor no debe ser mayor a {0} digitos.
        /// </summary>
        internal static string MessageMaxLength {
            get {
                return ResourceManager.GetString("MessageMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor no debe ser menor a {0} digitos.
        /// </summary>
        internal static string MessageMinLength {
            get {
                return ResourceManager.GetString("MessageMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese solo valores numericos.
        /// </summary>
        internal static string MessageNumber {
            get {
                return ResourceManager.GetString("MessageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Requerido.
        /// </summary>
        internal static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad no alcanzada para Alta de Credito.
        /// </summary>
        internal static string MinAgeCredit {
            get {
                return ResourceManager.GetString("MinAgeCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso Mensual.
        /// </summary>
        internal static string MonthlyIncome {
            get {
                return ResourceManager.GetString("MonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remuneración.
        /// </summary>
        internal static string MontlyIncome {
            get {
                return ResourceManager.GetString("MontlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Creditos.
        /// </summary>
        internal static string MyCredits {
            get {
                return ResourceManager.GetString("MyCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Créditos.
        /// </summary>
        internal static string MyCreditsDetail {
            get {
                return ResourceManager.GetString("MyCreditsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Datos.
        /// </summary>
        internal static string MyInfo {
            get {
                return ResourceManager.GetString("MyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidad.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Crédito.
        /// </summary>
        internal static string NewCredit {
            get {
                return ResourceManager.GetString("NewCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        internal static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupación.
        /// </summary>
        internal static string Ocupation {
            get {
                return ResourceManager.GetString("Ocupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKPreAuthorized {
            get {
                return ResourceManager.GetString("OKPreAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEN.
        /// </summary>
        internal static string PendingPreAuthorized {
            get {
                return ResourceManager.GetString("PendingPreAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Aciertos Obtenidos.
        /// </summary>
        internal static string PercentageAcquired {
            get {
                return ResourceManager.GetString("PercentageAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Aciertos Requeridos.
        /// </summary>
        internal static string PercentageRequired {
            get {
                return ResourceManager.GetString("PercentageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Particulares.
        /// </summary>
        internal static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód.Postal.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credito Pre-Autorizado! Continuar con la Validacion de Identidad.
        /// </summary>
        internal static string PreAuthorizedCredit {
            get {
                return ResourceManager.GetString("PreAuthorizedCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Pre-Autorizacion del Credito ha sido Anulada.
        /// </summary>
        internal static string PreAuthorizedCreditAnulled {
            get {
                return ResourceManager.GetString("PreAuthorizedCreditAnulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefijo.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas.
        /// </summary>
        internal static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas.
        /// </summary>
        internal static string Quotas {
            get {
                return ResourceManager.GetString("Quotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Nuevo Usuario.
        /// </summary>
        internal static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazado.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REC.
        /// </summary>
        internal static string RejectPreAuthorized {
            get {
                return ResourceManager.GetString("RejectPreAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacion.
        /// </summary>
        internal static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordarme?.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de la Solicitud.
        /// </summary>
        internal static string RequestData {
            get {
                return ResourceManager.GetString("RequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Solicitado.
        /// </summary>
        internal static string RequestedAmount {
            get {
                return ResourceManager.GetString("RequestedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Datos requeridos.
        /// </summary>
        internal static string RequiredData {
            get {
                return ResourceManager.GetString("RequiredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de Repuesta :.
        /// </summary>
        internal static string ResponseTime {
            get {
                return ResourceManager.GetString("ResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar a Detalle de Creditos.
        /// </summary>
        internal static string ReturnCreditsDetails {
            get {
                return ResourceManager.GetString("ReturnCreditsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar a Alta de Creditos.
        /// </summary>
        internal static string ReturnNewCredit {
            get {
                return ResourceManager.GetString("ReturnNewCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Seguridad .
        /// </summary>
        internal static string SecurityCode {
            get {
                return ResourceManager.GetString("SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Ocupacion.
        /// </summary>
        internal static string SelectOcupation {
            get {
                return ResourceManager.GetString("SelectOcupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Vendedor.
        /// </summary>
        internal static string SelectSeller {
            get {
                return ResourceManager.GetString("SelectSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Sexo.
        /// </summary>
        internal static string SelectSex {
            get {
                return ResourceManager.GetString("SelectSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        internal static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando Solicitud...
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Session Expiro!.
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesion iniciada.
        /// </summary>
        internal static string SessionInited {
            get {
                return ResourceManager.GetString("SessionInited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucursal.
        /// </summary>
        internal static string Subsidiary {
            get {
                return ResourceManager.GetString("Subsidiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imp. Cuotas.
        /// </summary>
        internal static string TaxQuotes {
            get {
                return ResourceManager.GetString("TaxQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono 2.
        /// </summary>
        internal static string Tel2 {
            get {
                return ResourceManager.GetString("Tel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono 3.
        /// </summary>
        internal static string Tel3 {
            get {
                return ResourceManager.GetString("Tel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        internal static string TelNumber {
            get {
                return ResourceManager.GetString("TelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Nro. debe tener {0} digitos.
        /// </summary>
        internal static string telNumberLong {
            get {
                return ResourceManager.GetString("telNumberLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Comercio.
        /// </summary>
        internal static string TradeCode {
            get {
                return ResourceManager.GetString("TradeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese a su cuenta para iniciar Sesion..
        /// </summary>
        internal static string UseLocalAccount {
            get {
                return ResourceManager.GetString("UseLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Usuario.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validacion de Identidad.
        /// </summary>
        internal static string ValidateIdentity {
            get {
                return ResourceManager.GetString("ValidateIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validacion.
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Datos de Identidad ya fueron verificados!.
        /// </summary>
        internal static string ValidationExist {
            get {
                return ResourceManager.GetString("ValidationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validacion Rechazada!.
        /// </summary>
        internal static string ValidationRejected {
            get {
                return ResourceManager.GetString("ValidationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de Validación.
        /// </summary>
        internal static string ValidationResult {
            get {
                return ResourceManager.GetString("ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domi. Laboral.
        /// </summary>
        internal static string WorkAddress {
            get {
                return ResourceManager.GetString("WorkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legajo.
        /// </summary>
        internal static string WorkFile {
            get {
                return ResourceManager.GetString("WorkFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel. Laboral.
        /// </summary>
        internal static string WorkingTel {
            get {
                return ResourceManager.GetString("WorkingTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiguedad Insuficiente para Alta de Credito.
        /// </summary>
        internal static string WorkSeniority {
            get {
                return ResourceManager.GetString("WorkSeniority", resourceCulture);
            }
        }
    }
}
